name: 'deploy-my-profile'
on: push

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    env:
      PUBLISH_FOLDER: src/bin/Release/net9.0/publish/wwwroot

    name: Build and Deploy Job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --output-path=dist/my-ng-profile --base-href=//${{ env.REPO_NAME }}/

      - name: Deploy to GH Pages
        run: npx angular-cli-ghpages --dir=dist/my-ng-profile
